### ISSUE TITLE
datasource dev mode

### ISSUE THREAD

**Issue by zirconias** [xxyy/tingo#1]
hi ,  i just cloned your work to see what it can be done.
and trying to run springBoot ,  i had a problem with datasource that could not autowire.

can you give us the way i can fix this ? 

thanks

**Comment by literalplus** [comment]
Hi,

this project is still a work in progress and I'm surprised that anyone
would want to use it without even knowing what it does.

Anyways, IntelliJ (if you're using that, which you should) is convinced
that the DataSource is not an available bean, but it actually is. Run the
project using `gradle bootRun`. Also make sure you have copied
`application.properties.example` in the root folder to
`application.properties` and filled in your correct (My)SQL credentials.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by literalplus** [comment]
Is this still an issue? If not, please close this.
